name: flutter_widget_from_html
version: 0.9.0+1
description: Flutter package to render html as widgets that supports hyperlink, image, audio, video, iframe and many other tags.
homepage: https://github.com/daohoangson/flutter_widget_from_html
environment:
  flutter: ">=3.3.0"
  sdk: ">=2.18.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_widget_from_html_core: 0.9.0
  fwfh_cached_network_image: ^0.7.0+3
  fwfh_chewie: ^0.7.0+3
  fwfh_just_audio: ^0.9.0
  fwfh_svg: ^0.7.2+1
  fwfh_url_launcher: ^0.9.0
  fwfh_webview: ^0.6.2+5
  html: ^0.15.0
dev_dependencies:
  file:
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.13.0
  lint: any
  mocktail: ^0.3.0
